In [9]:
library(tidyverse)
data("starwars", package = "dplyr")


glimpse(starwars)
# 87 Observations/Rows
# 14 Variables/Columns

Rows: 87
Columns: 14
$ name       <chr> "Luke Skywalker", "C-3PO", "R2-D2", "Darth Vader", "Leia Or…
$ height     <int> 172, 167, 96, 202, 150, 178, 165, 97, 183, 182, 188, 180, 2…
$ mass       <dbl> 77.0, 75.0, 32.0, 136.0, 49.0, 120.0, 75.0, 32.0, 84.0, 77.…
$ hair_color <chr> "blond", NA, NA, "none", "brown", "brown, grey", "brown", N…
$ skin_color <chr> "fair", "gold", "white, blue", "white", "light", "light", "…
$ eye_color  <chr> "blue", "yellow", "red", "yellow", "brown", "blue", "blue",…
$ birth_year <dbl> 19.0, 112.0, 33.0, 41.9, 19.0, 52.0, 47.0, NA, 24.0, 57.0, …
$ sex        <chr> "male", "none", "none", "male", "female", "male", "female",…
$ gender     <chr> "masculine", "masculine", "masculine", "masculine", "femini…
$ homeworld  <chr> "Tatooine", "Tatooine", "Naboo", "Tatooine", "Alderaan", "T…
$ species    <chr> "Human", "Droid", "Droid", "Human", "Human", "Human", "Huma…
$ films      <list> <"A New Hope", "The Empire Strikes Back", "Return of the J…
$ vehicles   <list> <"Snowspeeder", "Imperial Speeder Bike">, <>, <>, <>, "Imp…
$ starships  <list> <"X-wing", "Imperial shuttle">, <>, <>, "TIE Advanced x1",…

In [2]:
starwars %>%
  summarise(
    height_NA = sum(is.na(height)),
    mass_NA = sum(is.na(mass)),
    homeworld_NA = sum(is.na(homeworld))
  )

  height_NA mass_NA homeworld_NA
1 6         28      10

In [20]:
starwars_wide <- starwars %>%
  #Keep only rows with non-missing species
  filter(!is.na(species)) %>%
  
  #Group by species and gender
  group_by(species, gender) %>%
  
  #Compute mean height per group
  summarise(mean_height = mean(height, na.rm = TRUE), .groups = "drop") %>%
  
  #Pivot wider: species as rows, gender as columns
  pivot_wider(
    names_from = gender,
    values_from = mean_height
  )

starwars_wide

   species        masculine feminine
1  Aleena          79.0000        NA
2  Besalisk       198.0000        NA
3  Cerean         198.0000        NA
4  Chagrian       196.0000        NA
5  Clawdite             NA  168.0000
6  Droid          140.0000   96.0000
7  Dug            112.0000        NA
8  Ewok            88.0000        NA
9  Geonosian      183.0000        NA
10 Gungan         208.6667        NA
11 Human          182.3913  163.5714
12 Hutt           175.0000        NA
13 Iktotchi       188.0000        NA
14 Kaleesh        216.0000        NA
15 Kaminoan       229.0000  213.0000
16 Kel Dor        188.0000        NA
17 Mirialan             NA  168.0000
18 Mon Calamari   180.0000        NA
19 Muun           191.0000        NA
20 Nautolan       196.0000        NA
21 Neimodian      191.0000        NA
22 Pau'an         206.0000        NA
23 Quermian       264.0000        NA
24 Rodian         173.0000        NA
25 Skakoan        193.0000        NA
26 Sullustan      160.0000        NA
27 Tholothian           NA  184.0000
28 Togruta              NA  178.0000
29 Toong          163.0000        NA
30 Toydarian      137.0000        NA
31 Trandoshan     190.0000        NA
32 Twi'lek        180.0000  178.0000
33 Vulptereen      94.0000        NA
34 Wookiee        231.0000        NA
35 Xexto          122.0000        NA
36 Yoda's species  66.0000        NA
37 Zabrak         173.0000        NA

In [25]:
#Pivot Longer: species as rows, mean height/gender as columns
starwars_long <- starwars_wide %>%  
    pivot_longer(
        cols = -species,
        names_to = "gender",
        values_to = "mean_height"
      ) %>%
    filter(!is.na(mean_height))

starwars_long

   species        gender    mean_height
1  Aleena         masculine  79.0000
2  Besalisk       masculine 198.0000
3  Cerean         masculine 198.0000
4  Chagrian       masculine 196.0000
5  Clawdite       feminine  168.0000
6  Droid          masculine 140.0000
7  Droid          feminine   96.0000
8  Dug            masculine 112.0000
9  Ewok           masculine  88.0000
10 Geonosian      masculine 183.0000
11 Gungan         masculine 208.6667
12 Human          masculine 182.3913
13 Human          feminine  163.5714
14 Hutt           masculine 175.0000
15 Iktotchi       masculine 188.0000
16 Kaleesh        masculine 216.0000
17 Kaminoan       masculine 229.0000
18 Kaminoan       feminine  213.0000
19 Kel Dor        masculine 188.0000
20 Mirialan       feminine  168.0000
21 Mon Calamari   masculine 180.0000
22 Muun           masculine 191.0000
23 Nautolan       masculine 196.0000
24 Neimodian      masculine 191.0000
25 Pau'an         masculine 206.0000
26 Quermian       masculine 264.0000
27 Rodian         masculine 173.0000
28 Skakoan        masculine 193.0000
29 Sullustan      masculine 160.0000
30 Tholothian     feminine  184.0000
31 Togruta        feminine  178.0000
32 Toong          masculine 163.0000
33 Toydarian      masculine 137.0000
34 Trandoshan     masculine 190.0000
35 Twi'lek        masculine 180.0000
36 Twi'lek        feminine  178.0000
37 Vulptereen     masculine  94.0000
38 Wookiee        masculine 231.0000
39 Xexto          masculine 122.0000
40 Yoda's species masculine  66.0000
41 Zabrak         masculine 173.0000

In [27]:
starwars_bmi <- starwars %>%
  mutate(
    # BMI = mass / (height/100)^2
    BMI = mass / ( (height/100)^2 ),
    
    # Height category
    height_category = case_when(
      height < 170            ~ "short",
      height >= 170 & height <= 189 ~ "average",
      height >= 190           ~ "tall",
      TRUE                    ~ NA_character_  # keep NA if height is missing
    ),
    
    # Replace missing homeworld with "Unknown"
    homeworld = if_else(is.na(homeworld), "Unknown", homeworld)
  )

glimpse(starwars_bmi)

Rows: 87
Columns: 16
$ name            <chr> "Luke Skywalker", "C-3PO", "R2-D2", "Darth Vader", "Le…
$ height          <int> 172, 167, 96, 202, 150, 178, 165, 97, 183, 182, 188, 1…
$ mass            <dbl> 77.0, 75.0, 32.0, 136.0, 49.0, 120.0, 75.0, 32.0, 84.0…
$ hair_color      <chr> "blond", NA, NA, "none", "brown", "brown, grey", "brow…
$ skin_color      <chr> "fair", "gold", "white, blue", "white", "light", "ligh…
$ eye_color       <chr> "blue", "yellow", "red", "yellow", "brown", "blue", "b…
$ birth_year      <dbl> 19.0, 112.0, 33.0, 41.9, 19.0, 52.0, 47.0, NA, 24.0, 5…
$ sex             <chr> "male", "none", "none", "male", "female", "male", "fem…
$ gender          <chr> "masculine", "masculine", "masculine", "masculine", "f…
$ homeworld       <chr> "Tatooine", "Tatooine", "Naboo", "Tatooine", "Alderaan…
$ species         <chr> "Human", "Droid", "Droid", "Human", "Human", "Human", …
$ films           <list> <"A New Hope", "The Empire Strikes Back", "Return of …
$ vehicles        <list> <"Snowspeeder", "Imperial Speeder Bike">, <>, <>, <>,…
$ starships       <list> <"X-wing", "Imperial shuttle">, <>, <>, "TIE Advanced…
$ BMI             <dbl> 26.02758, 26.89232, 34.72222, 33.33007, 21.77778, 37.8…
$ height_category <chr> "average", "short", "short", "tall", "short", "average…

In [28]:

starwars_bmi_display <- starwars_bmi %>%
  mutate(
    films = sapply(films, paste, collapse = ", "),
    species = sapply(species, paste, collapse = ", "),
    vehicles = sapply(vehicles, paste, collapse = ", "),
    starships = sapply(starships, paste, collapse = ", ")
  )

# Display with rich
starwars_bmi_display

   name                  height mass   hair_color    skin_color
1  Luke Skywalker        172      77.0 blond         fair
2  C-3PO                 167      75.0 NA            gold
3  R2-D2                  96      32.0 NA            white, blue
4  Darth Vader           202     136.0 none          white
5  Leia Organa           150      49.0 brown         light
6  Owen Lars             178     120.0 brown, grey   light
7  Beru Whitesun Lars    165      75.0 brown         light
8  R5-D4                  97      32.0 NA            white, red
9  Biggs Darklighter     183      84.0 black         light
10 Obi-Wan Kenobi        182      77.0 auburn, white fair
11 Anakin Skywalker      188      84.0 blond         fair
12 Wilhuff Tarkin        180        NA auburn, grey  fair
13 Chewbacca             228     112.0 brown         unknown
14 Han Solo              180      80.0 brown         fair
15 Greedo                173      74.0 NA            green
16 Jabba Desilijic Tiure 175    1358.0 NA            green-tan, brown
17 Wedge Antilles        170      77.0 brown         fair
18 Jek Tono Porkins      180     110.0 brown         fair
19 Yoda                   66      17.0 white         green
20 Palpatine             170      75.0 grey          pale
21 Boba Fett             183      78.2 black         fair
22 IG-88                 200     140.0 none          metal
23 Bossk                 190     113.0 none          green
24 Lando Calrissian      177      79.0 black         dark
25 Lobot                 175      79.0 none          light
26 Ackbar                180      83.0 none          brown mottle
27 Mon Mothma            150        NA auburn        fair
28 Arvel Crynyd           NA        NA brown         fair
29 Wicket Systri Warrick  88      20.0 brown         brown
30 Nien Nunb             160      68.0 none          grey
⋮  ⋮                     ⋮      ⋮      ⋮             ⋮
58 Mas Amedda            196       NA  none          blue
59 Gregar Typho          185     85.0  black         dark
60 Cordé                 157       NA  brown         light
61 Cliegg Lars           183       NA  brown         fair
62 Poggle the Lesser     183     80.0  none          green
63 Luminara Unduli       170     56.2  black         yellow
64 Barriss Offee         166     50.0  black         yellow
65 Dormé                 165       NA  brown         light
66 Dooku                 193     80.0  white         fair
67 Bail Prestor Organa   191       NA  black         tan
68 Jango Fett            183     79.0  black         tan
69 Zam Wesell            168     55.0  blonde        fair, green, yellow
70 Dexter Jettster       198    102.0  none          brown
71 Lama Su               229     88.0  none          grey
72 Taun We               213       NA  none          grey
73 Jocasta Nu            167       NA  white         fair
74 R4-P17                 96       NA  none          silver, red
75 Wat Tambor            193     48.0  none          green, grey
76 San Hill              191       NA  none          grey
77 Shaak Ti              178     57.0  none          red, blue, white
78 Grievous              216    159.0  none          brown, white
79 Tarfful               234    136.0  brown         brown
80 Raymus Antilles       188     79.0  brown         light
81 Sly Moore             178     48.0  none          pale
82 Tion Medon            206     80.0  none          grey
83 Finn                   NA       NA  black         dark
84 Rey                    NA       NA  brown         light
85 Poe Dameron            NA       NA  brown         light
86 BB8                    NA       NA  none          none
87 Captain Phasma         NA       NA  none          none
   eye_color     birth_year sex            gender    homeworld
1  blue           19.0      male           masculine Tatooine
2  yellow        112.0      none           masculine Tatooine
3  red            33.0      none           masculine Naboo
4  yellow         41.9      male           masculine Tatooine
5  brown          19.0      female         feminine  Alderaan
6  blue           52.0      male           masculine Tatooine
7  blue           47.0      female         feminine  Tatooine
8  red              NA      none           masculine Tatooine
9  brown          24.0      male           masculine Tatooine
10 blue-gray      57.0      male           masculine Stewjon
11 blue           41.9      male           masculine Tatooine
12 blue           64.0      male           masculine Eriadu
13 blue          200.0      male           masculine Kashyyyk
14 brown          29.0      male           masculine Corellia
15 black          44.0      male           masculine Rodia
16 orange        600.0      hermaphroditic masculine Nal Hutta
17 hazel          21.0      male           masculine Corellia
18 blue             NA      NA             NA        Bestine IV
19 brown         896.0      male           masculine Unknown
20 yellow         82.0      male           masculine Naboo
21 brown          31.5      male           masculine Kamino
22 red            15.0      none           masculine Unknown
23 red            53.0      male           masculine Trandosha
24 brown          31.0      male           masculine Socorro
25 blue           37.0      male           masculine Bespin
26 orange         41.0      male           masculine Mon Cala
27 blue           48.0      female         feminine  Chandrila
28 brown            NA      male           masculine Unknown
29 brown           8.0      male           masculine Endor
30 black            NA      male           masculine Sullust
⋮  ⋮             ⋮          ⋮              ⋮         ⋮
58 blue           NA        male           masculine Champala
59 brown          NA        NA             NA        Naboo
60 brown          NA        NA             NA        Naboo
61 blue           82        male           masculine Tatooine
62 yellow         NA        male           masculine Geonosis
63 blue           58        female         feminine  Mirial
64 blue           40        female         feminine  Mirial
65 brown          NA        female         feminine  Naboo
66 brown         102        male           masculine Serenno
67 brown          67        male           masculine Alderaan
68 brown          66        male           masculine Concord Dawn
69 yellow         NA        female         feminine  Zolan
70 yellow         NA        male           masculine Ojom
71 black          NA        male           masculine Kamino
72 black          NA        female         feminine  Kamino
73 blue           NA        female         feminine  Coruscant
74 red, blue      NA        none           feminine  Unknown
75 unknown        NA        male           masculine Skako
76 gold           NA        male           masculine Muunilinst
77 black          NA        female         feminine  Shili
78 green, yellow  NA        male           masculine Kalee
79 blue           NA        male           masculine Kashyyyk
80 brown          NA        male           masculine Alderaan
81 white          NA        NA             NA        Umbara
82 black          NA        male           masculine Utapau
83 dark           NA        male           masculine Unknown
84 hazel          NA        female         feminine  Unknown
85 brown          NA        male           masculine Unknown
86 black          NA        none           masculine Unknown
87 unknown        NA        female         feminine  Unknown
   species
1  Human
2  Droid
3  Droid
4  Human
5  Human
6  Human
7  Human
8  Droid
9  Human
10 Human
11 Human
12 Human
13 Wookiee
14 Human
15 Rodian
16 Hutt
17 Human
18 NA
19 Yoda's species
20 Human
21 Human
22 Droid
23 Trandoshan
24 Human
25 Human
26 Mon Calamari
27 Human
28 Human
29 Ewok
30 Sullustan
⋮  ⋮
58 Chagrian
59 NA
60 NA
61 Human
62 Geonosian
63 Mirialan
64 Mirialan
65 Human
66 Human
67 Human
68 Human
69 Clawdite
70 Besalisk
71 Kaminoan
72 Kaminoan
73 Human
74 Droid
75 Skakoan
76 Muun
77 Togruta
78 Kaleesh
79 Wookiee
80 Human
81 NA
82 Pau'an
83 Human
84 Human
85 Human
86 Droid
87 Human
   films
1  A New Hope, The Empire Strikes Back, Return of the Jedi, Revenge of the Sith, The Force Awakens
2  A New Hope, The Empire Strikes Back, Return of the Jedi, The Phantom Menace, Attack of the Clones, Revenge of the Sith
3  A New Hope, The Empire Strikes Back, Return of the Jedi, The Phantom Menace, Attack of the Clones, Revenge of the Sith, The Force Awakens
4  A New Hope, The Empire Strikes Back, Return of the Jedi, Revenge of the Sith
5  A New Hope, The Empire Strikes Back, Return of the Jedi, Revenge of the Sith, The Force Awakens
6  A New Hope, Attack of the Clones, Revenge of the Sith
7  A New Hope, Attack of the Clones, Revenge of the Sith
8  A New Hope
9  A New Hope
10 A New Hope, The Empire Strikes Back, Return of the Jedi, The Phantom Menace, Attack of the Clones, Revenge of the Sith
11 The Phantom Menace, Attack of the Clones, Revenge of the Sith
12 A New Hope, Revenge of the Sith
13 A New Hope, The Empire Strikes Back, Return of the Jedi, Revenge of the Sith, The Force Awakens
14 A New Hope, The Empire Strikes Back, Return of the Jedi, The Force Awakens
15 A New Hope
16 A New Hope, Return of the Jedi, The Phantom Menace
17 A New Hope, The Empire Strikes Back, Return of the Jedi
18 A New Hope
19 The Empire Strikes Back, Return of the Jedi, The Phantom Menace, Attack of the Clones, Revenge of the Sith
20 The Empire Strikes Back, Return of the Jedi, The Phantom Menace, Attack of the Clones, Revenge of the Sith
21 The Empire Strikes Back, Return of the Jedi, Attack of the Clones
22 The Empire Strikes Back
23 The Empire Strikes Back
24 The Empire Strikes Back, Return of the Jedi
25 The Empire Strikes Back
26 Return of the Jedi, The Force Awakens
27 Return of the Jedi
28 Return of the Jedi
29 Return of the Jedi
30 Return of the Jedi
⋮  ⋮
58 The Phantom Menace, Attack of the Clones
59 Attack of the Clones
60 Attack of the Clones
61 Attack of the Clones
62 Attack of the Clones, Revenge of the Sith
63 Attack of the Clones, Revenge of the Sith
64 Attack of the Clones
65 Attack of the Clones
66 Attack of the Clones, Revenge of the Sith
67 Attack of the Clones, Revenge of the Sith
68 Attack of the Clones
69 Attack of the Clones
70 Attack of the Clones
71 Attack of the Clones
72 Attack of the Clones
73 Attack of the Clones
74 Attack of the Clones, Revenge of the Sith
75 Attack of the Clones
76 Attack of the Clones
77 Attack of the Clones, Revenge of the Sith
78 Revenge of the Sith
79 Revenge of the Sith
80 A New Hope, Revenge of the Sith
81 Attack of the Clones, Revenge of the Sith
82 Revenge of the Sith
83 The Force Awakens
84 The Force Awakens
85 The Force Awakens
86 The Force Awakens
87 The Force Awakens
   vehicles
1  Snowspeeder, Imperial Speeder Bike
2
3
4
5  Imperial Speeder Bike
6
7
8
9
10 Tribubble bongo
11 Zephyr-G swoop bike, XJ-6 airspeeder
12
13 AT-ST
14
15
16
17 Snowspeeder
18
19
20
21
22
23
24
25
26
27
28
29
30
⋮  ⋮
58
59
60
61
62
63
64
65
66 Flitknot speeder
67
68
69 Koro-2 Exodrive airspeeder
70
71
72
73
74
75
76
77
78 Tsmeu-6 personal wheel bike
79
80
81
82
83
84
85
86
87
   starships
1  X-wing, Imperial shuttle
2
3
4  TIE Advanced x1
5
6
7
8
9  X-wing
10 Jedi starfighter, Trade Federation cruiser, Naboo star skiff, Jedi Interceptor, Belbullab-22 starfighter
11 Naboo fighter, Trade Federation cruiser, Jedi Interceptor
12
13 Millennium Falcon, Imperial shuttle
14 Millennium Falcon, Imperial shuttle
15
16
17 X-wing
18 X-wing
19
20
21 Slave 1
22
23
24 Millennium Falcon
25
26
27
28 A-wing
29
30 Millennium Falcon
⋮  ⋮
58
59 Naboo fighter
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78 Belbullab-22 starfighter
79
80
81
82
83
84
85 X-wing
86
87
   BMI       height_category
1   26.02758 average
2   26.89232 short
3   34.72222 short
4   33.33007 tall
5   21.77778 short
6   37.87401 average
7   27.54821 short
8   34.00999 short
9   25.08286 average
10  23.24598 average
11  23.76641 average
12        NA average
13  21.54509 tall
14  24.69136 average
15  24.72518 average
16 443.42857 average
17  26.64360 average
18  33.95062 average
19  39.02663 short
20  25.95156 average
21  23.35095 average
22  35.00000 tall
23  31.30194 tall
24  25.21625 average
25  25.79592 average
26  25.61728 average
27        NA short
28        NA NA
29  25.82645 short
30  26.56250 short
⋮  ⋮         ⋮
58       NA  tall
59 24.83565  average
60       NA  short
61       NA  average
62 23.88844  average
63 19.44637  average
64 18.14487  short
65       NA  short
66 21.47709  tall
67       NA  tall
68 23.58984  average
69 19.48696  short
70 26.01775  tall
71 16.78076  tall
72       NA  tall
73       NA  short
74       NA  short
75 12.88625  tall
76       NA  tall
77 17.99015  average
78 34.07922  tall
79 24.83746  tall
80 22.35174  average
81 15.14960  average
82 18.85192  tall
83       NA  NA
84       NA  NA
85       NA  NA
86       NA  NA
87       NA  NA

In [29]:
starwars %>%
  select(name, films) %>%              # keep only relevant columns
  unnest_longer(films) %>%             # convert list-column into long format
  group_by(name) %>%                    # group by character
  summarise(film_count = n(), .groups = "drop") %>%  # count number of films
  arrange(desc(film_count)) %>%         # sort descending
  slice_head(n = 8)

  name           film_count
1 R2-D2          7
2 C-3PO          6
3 Obi-Wan Kenobi 6
4 Chewbacca      5
5 Leia Organa    5
6 Luke Skywalker 5
7 Palpatine      5
8 Yoda           5

Because long data makes it easier to work with variables and observations by having 1:1 relation/ratio of data, we can use tiderveryse tools to get our desired output from those data that will be harder if they are not in the long format. Most plotting and analysis is also easier and more digestible to be understood by functions and readable by humans due to less indexing/wordy or long values.